export const countries = [
  {
    name: "Afghanistan",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    code: "AF",
    areaCode: "93",
  },
  {
    name: "Åland Islands",
    flag: "https://flagcdn.com/ax.svg",
    code: "AX",
    areaCode: "358",
  },
  {
    name: "Albania",
    flag: "https://flagcdn.com/al.svg",
    code: "AL",
    areaCode: "355",
  },
  {
    name: "Algeria",
    flag: "https://flagcdn.com/dz.svg",
    code: "DZ",
    areaCode: "213",
  },
  {
    name: "American Samoa",
    flag: "https://flagcdn.com/as.svg",
    code: "AS",
    areaCode: "1",
  },
  {
    name: "Andorra",
    flag: "https://flagcdn.com/ad.svg",
    code: "AD",
    areaCode: "376",
  },
  {
    name: "Angola",
    flag: "https://flagcdn.com/ao.svg",
    code: "AO",
    areaCode: "244",
  },
  {
    name: "Anguilla",
    flag: "https://flagcdn.com/ai.svg",
    code: "AI",
    areaCode: "1",
  },
  {
    name: "Antarctica",
    flag: "https://flagcdn.com/aq.svg",
    code: "AQ",
    areaCode: "672",
  },
  {
    name: "Antigua and Barbuda",
    flag: "https://flagcdn.com/ag.svg",
    code: "AG",
    areaCode: "1",
  },
  {
    name: "Argentina",
    flag: "https://flagcdn.com/ar.svg",
    code: "AR",
    areaCode: "54",
  },
  {
    name: "Armenia",
    flag: "https://flagcdn.com/am.svg",
    code: "AM",
    areaCode: "374",
  },
  {
    name: "Aruba",
    flag: "https://flagcdn.com/aw.svg",
    code: "AW",
    areaCode: "297",
  },
  {
    name: "Australia",
    flag: "https://flagcdn.com/au.svg",
    code: "AU",
    areaCode: "61",
  },
  {
    name: "Austria",
    flag: "https://flagcdn.com/at.svg",
    code: "AT",
    areaCode: "43",
  },
  {
    name: "Azerbaijan",
    flag: "https://flagcdn.com/az.svg",
    code: "AZ",
    areaCode: "994",
  },
  {
    name: "Bahamas",
    flag: "https://flagcdn.com/bs.svg",
    code: "BS",
    areaCode: "1",
  },
  {
    name: "Bahrain",
    flag: "https://flagcdn.com/bh.svg",
    code: "BH",
    areaCode: "973",
  },
  {
    name: "Bangladesh",
    flag: "https://flagcdn.com/bd.svg",
    code: "BD",
    areaCode: "880",
  },
  {
    name: "Barbados",
    flag: "https://flagcdn.com/bb.svg",
    code: "BB",
    areaCode: "1",
  },
  {
    name: "Belarus",
    flag: "https://flagcdn.com/by.svg",
    code: "BY",
    areaCode: "375",
  },
  {
    name: "Belgium",
    flag: "https://flagcdn.com/be.svg",
    code: "BE",
    areaCode: "32",
  },
  {
    name: "Belize",
    flag: "https://flagcdn.com/bz.svg",
    code: "BZ",
    areaCode: "501",
  },
  {
    name: "Benin",
    flag: "https://flagcdn.com/bj.svg",
    code: "BJ",
    areaCode: "229",
  },
  {
    name: "Bermuda",
    flag: "https://flagcdn.com/bm.svg",
    code: "BM",
    areaCode: "1",
  },
  {
    name: "Bhutan",
    flag: "https://flagcdn.com/bt.svg",
    code: "BT",
    areaCode: "975",
  },
  {
    name: "Bolivia (Plurinational State of)",
    flag: "https://flagcdn.com/bo.svg",
    code: "BO",
    areaCode: "591",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    flag: "https://flagcdn.com/bq.svg",
    code: "BQ",
    areaCode: "599",
  },
  {
    name: "Bosnia and Herzegovina",
    flag: "https://flagcdn.com/ba.svg",
    code: "BA",
    areaCode: "387",
  },
  {
    name: "Botswana",
    flag: "https://flagcdn.com/bw.svg",
    code: "BW",
    areaCode: "267",
  },
  {
    name: "Bouvet Island",
    flag: "https://flagcdn.com/bv.svg",
    code: "BV",
    areaCode: "47",
  },
  {
    name: "Brazil",
    flag: "https://flagcdn.com/br.svg",
    code: "BR",
    areaCode: "55",
  },
  {
    name: "British Indian Ocean Territory",
    flag: "https://flagcdn.com/io.svg",
    code: "IO",
    areaCode: "246",
  },
  {
    name: "United States Minor Outlying Islands",
    flag: "https://flagcdn.com/um.svg",
    code: "UM",
    areaCode: "246",
  },
  {
    name: "Virgin Islands (British)",
    flag: "https://flagcdn.com/vg.svg",
    code: "VG",
    areaCode: "1",
  },
  {
    name: "Virgin Islands (U.S.)",
    flag: "https://flagcdn.com/vi.svg",
    code: "VI",
    areaCode: "1 340",
  },
  {
    name: "Brunei Darussalam",
    flag: "https://flagcdn.com/bn.svg",
    code: "BN",
    areaCode: "673",
  },
  {
    name: "Bulgaria",
    flag: "https://flagcdn.com/bg.svg",
    code: "BG",
    areaCode: "359",
  },
  {
    name: "Burkina Faso",
    flag: "https://flagcdn.com/bf.svg",
    code: "BF",
    areaCode: "226",
  },
  {
    name: "Burundi",
    flag: "https://flagcdn.com/bi.svg",
    code: "BI",
    areaCode: "257",
  },
  {
    name: "Cambodia",
    flag: "https://flagcdn.com/kh.svg",
    code: "KH",
    areaCode: "855",
  },
  {
    name: "Cameroon",
    flag: "https://flagcdn.com/cm.svg",
    code: "CM",
    areaCode: "237",
  },
  {
    name: "Canada",
    flag: "https://flagcdn.com/ca.svg",
    code: "CA",
    areaCode: "1",
  },
  {
    name: "Cabo Verde",
    flag: "https://flagcdn.com/cv.svg",
    code: "CV",
    areaCode: "238",
  },
  {
    name: "Cayman Islands",
    flag: "https://flagcdn.com/ky.svg",
    code: "KY",
    areaCode: "1",
  },
  {
    name: "Central African Republic",
    flag: "https://flagcdn.com/cf.svg",
    code: "CF",
    areaCode: "236",
  },
  {
    name: "Chad",
    flag: "https://flagcdn.com/td.svg",
    code: "TD",
    areaCode: "235",
  },
  {
    name: "Chile",
    flag: "https://flagcdn.com/cl.svg",
    code: "CL",
    areaCode: "56",
  },
  {
    name: "China",
    flag: "https://flagcdn.com/cn.svg",
    code: "CN",
    areaCode: "86",
  },
  {
    name: "Christmas Island",
    flag: "https://flagcdn.com/cx.svg",
    code: "CX",
    areaCode: "61",
  },
  {
    name: "Cocos (Keeling) Islands",
    flag: "https://flagcdn.com/cc.svg",
    code: "CC",
    areaCode: "61",
  },
  {
    name: "Colombia",
    flag: "https://flagcdn.com/co.svg",
    code: "CO",
    areaCode: "57",
  },
  {
    name: "Comoros",
    flag: "https://flagcdn.com/km.svg",
    code: "KM",
    areaCode: "269",
  },
  {
    name: "Congo",
    flag: "https://flagcdn.com/cg.svg",
    code: "CG",
    areaCode: "242",
  },
  {
    name: "Congo (Democratic Republic of the)",
    flag: "https://flagcdn.com/cd.svg",
    code: "CD",
    areaCode: "243",
  },
  {
    name: "Cook Islands",
    flag: "https://flagcdn.com/ck.svg",
    code: "CK",
    areaCode: "682",
  },
  {
    name: "Costa Rica",
    flag: "https://flagcdn.com/cr.svg",
    code: "CR",
    areaCode: "506",
  },
  {
    name: "Croatia",
    flag: "https://flagcdn.com/hr.svg",
    code: "HR",
    areaCode: "385",
  },
  {
    name: "Cuba",
    flag: "https://flagcdn.com/cu.svg",
    code: "CU",
    areaCode: "53",
  },
  {
    name: "Curaçao",
    flag: "https://flagcdn.com/cw.svg",
    code: "CW",
    areaCode: "599",
  },
  {
    name: "Cyprus",
    flag: "https://flagcdn.com/cy.svg",
    code: "CY",
    areaCode: "357",
  },
  {
    name: "Czech Republic",
    flag: "https://flagcdn.com/cz.svg",
    code: "CZ",
    areaCode: "420",
  },
  {
    name: "Denmark",
    flag: "https://flagcdn.com/dk.svg",
    code: "DK",
    areaCode: "45",
  },
  {
    name: "Djibouti",
    flag: "https://flagcdn.com/dj.svg",
    code: "DJ",
    areaCode: "253",
  },
  {
    name: "Dominica",
    flag: "https://flagcdn.com/dm.svg",
    code: "DM",
    areaCode: "1",
  },
  {
    name: "Dominican Republic",
    flag: "https://flagcdn.com/do.svg",
    code: "DO",
    areaCode: "1",
  },
  {
    name: "Ecuador",
    flag: "https://flagcdn.com/ec.svg",
    code: "EC",
    areaCode: "593",
  },
  {
    name: "Egypt",
    flag: "https://flagcdn.com/eg.svg",
    code: "EG",
    areaCode: "20",
  },
  {
    name: "El Salvador",
    flag: "https://flagcdn.com/sv.svg",
    code: "SV",
    areaCode: "503",
  },
  {
    name: "Equatorial Guinea",
    flag: "https://flagcdn.com/gq.svg",
    code: "GQ",
    areaCode: "240",
  },
  {
    name: "Eritrea",
    flag: "https://flagcdn.com/er.svg",
    code: "ER",
    areaCode: "291",
  },
  {
    name: "Estonia",
    flag: "https://flagcdn.com/ee.svg",
    code: "EE",
    areaCode: "372",
  },
  {
    name: "Ethiopia",
    flag: "https://flagcdn.com/et.svg",
    code: "ET",
    areaCode: "251",
  },
  {
    name: "Falkland Islands (Malvinas)",
    flag: "https://flagcdn.com/fk.svg",
    code: "FK",
    areaCode: "500",
  },
  {
    name: "Faroe Islands",
    flag: "https://flagcdn.com/fo.svg",
    code: "FO",
    areaCode: "298",
  },
  {
    name: "Fiji",
    flag: "https://flagcdn.com/fj.svg",
    code: "FJ",
    areaCode: "679",
  },
  {
    name: "Finland",
    flag: "https://flagcdn.com/fi.svg",
    code: "FI",
    areaCode: "358",
  },
  {
    name: "France",
    flag: "https://flagcdn.com/fr.svg",
    code: "FR",
    areaCode: "33",
  },
  {
    name: "French Guiana",
    flag: "https://flagcdn.com/gf.svg",
    code: "GF",
    areaCode: "594",
  },
  {
    name: "French Polynesia",
    flag: "https://flagcdn.com/pf.svg",
    code: "PF",
    areaCode: "689",
  },
  {
    name: "French Southern Territories",
    flag: "https://flagcdn.com/tf.svg",
    code: "TF",
    areaCode: "262",
  },
  {
    name: "Gabon",
    flag: "https://flagcdn.com/ga.svg",
    code: "GA",
    areaCode: "241",
  },
  {
    name: "Gambia",
    flag: "https://flagcdn.com/gm.svg",
    code: "GM",
    areaCode: "220",
  },
  {
    name: "Georgia",
    flag: "https://flagcdn.com/ge.svg",
    code: "GE",
    areaCode: "995",
  },
  {
    name: "Germany",
    flag: "https://flagcdn.com/de.svg",
    code: "DE",
    areaCode: "49",
  },
  {
    name: "Ghana",
    flag: "https://flagcdn.com/gh.svg",
    code: "GH",
    areaCode: "233",
  },
  {
    name: "Gibraltar",
    flag: "https://flagcdn.com/gi.svg",
    code: "GI",
    areaCode: "350",
  },
  {
    name: "Greece",
    flag: "https://flagcdn.com/gr.svg",
    code: "GR",
    areaCode: "30",
  },
  {
    name: "Greenland",
    flag: "https://flagcdn.com/gl.svg",
    code: "GL",
    areaCode: "299",
  },
  {
    name: "Grenada",
    flag: "https://flagcdn.com/gd.svg",
    code: "GD",
    areaCode: "1",
  },
  {
    name: "Guadeloupe",
    flag: "https://flagcdn.com/gp.svg",
    code: "GP",
    areaCode: "590",
  },
  {
    name: "Guam",
    flag: "https://flagcdn.com/gu.svg",
    code: "GU",
    areaCode: "1",
  },
  {
    name: "Guatemala",
    flag: "https://flagcdn.com/gt.svg",
    code: "GT",
    areaCode: "502",
  },
  {
    name: "Guernsey",
    flag: "https://flagcdn.com/gg.svg",
    code: "GG",
    areaCode: "44",
  },
  {
    name: "Guinea",
    flag: "https://flagcdn.com/gn.svg",
    code: "GN",
    areaCode: "224",
  },
  {
    name: "Guinea-Bissau",
    flag: "https://flagcdn.com/gw.svg",
    code: "GW",
    areaCode: "245",
  },
  {
    name: "Guyana",
    flag: "https://flagcdn.com/gy.svg",
    code: "GY",
    areaCode: "592",
  },
  {
    name: "Haiti",
    flag: "https://flagcdn.com/ht.svg",
    code: "HT",
    areaCode: "509",
  },
  {
    name: "Heard Island and McDonald Islands",
    flag: "https://flagcdn.com/hm.svg",
    code: "HM",
    areaCode: "672",
  },
  {
    name: "Vatican City",
    flag: "https://flagcdn.com/va.svg",
    code: "VA",
    areaCode: "379",
  },
  {
    name: "Honduras",
    flag: "https://flagcdn.com/hn.svg",
    code: "HN",
    areaCode: "504",
  },
  {
    name: "Hungary",
    flag: "https://flagcdn.com/hu.svg",
    code: "HU",
    areaCode: "36",
  },
  {
    name: "Hong Kong",
    flag: "https://flagcdn.com/hk.svg",
    code: "HK",
    areaCode: "852",
  },
  {
    name: "Iceland",
    flag: "https://flagcdn.com/is.svg",
    code: "IS",
    areaCode: "354",
  },
  {
    name: "India",
    flag: "https://flagcdn.com/in.svg",
    code: "IN",
    areaCode: "91",
  },
  {
    name: "Indonesia",
    flag: "https://flagcdn.com/id.svg",
    code: "ID",
    areaCode: "62",
  },
  {
    name: "Ivory Coast",
    flag: "https://flagcdn.com/ci.svg",
    code: "CI",
    areaCode: "225",
  },
  {
    name: "Iran (Islamic Republic of)",
    flag: "https://flagcdn.com/ir.svg",
    code: "IR",
    areaCode: "98",
  },
  {
    name: "Iraq",
    flag: "https://flagcdn.com/iq.svg",
    code: "IQ",
    areaCode: "964",
  },
  {
    name: "Ireland",
    flag: "https://flagcdn.com/ie.svg",
    code: "IE",
    areaCode: "353",
  },
  {
    name: "Isle of Man",
    flag: "https://flagcdn.com/im.svg",
    code: "IM",
    areaCode: "44",
  },
  {
    name: "Israel",
    flag: "https://flagcdn.com/il.svg",
    code: "IL",
    areaCode: "972",
  },
  {
    name: "Italy",
    flag: "https://flagcdn.com/it.svg",
    code: "IT",
    areaCode: "39",
  },
  {
    name: "Jamaica",
    flag: "https://flagcdn.com/jm.svg",
    code: "JM",
    areaCode: "1",
  },
  {
    name: "Japan",
    flag: "https://flagcdn.com/jp.svg",
    code: "JP",
    areaCode: "81",
  },
  {
    name: "Jersey",
    flag: "https://flagcdn.com/je.svg",
    code: "JE",
    areaCode: "44",
  },
  {
    name: "Jordan",
    flag: "https://flagcdn.com/jo.svg",
    code: "JO",
    areaCode: "962",
  },
  {
    name: "Kazakhstan",
    flag: "https://flagcdn.com/kz.svg",
    code: "KZ",
    areaCode: "76",
  },
  {
    name: "Kenya",
    flag: "https://flagcdn.com/ke.svg",
    code: "KE",
    areaCode: "254",
  },
  {
    name: "Kiribati",
    flag: "https://flagcdn.com/ki.svg",
    code: "KI",
    areaCode: "686",
  },
  {
    name: "Kuwait",
    flag: "https://flagcdn.com/kw.svg",
    code: "KW",
    areaCode: "965",
  },
  {
    name: "Kyrgyzstan",
    flag: "https://flagcdn.com/kg.svg",
    code: "KG",
    areaCode: "996",
  },
  {
    name: "Lao People's Democratic Republic",
    flag: "https://flagcdn.com/la.svg",
    code: "LA",
    areaCode: "856",
  },
  {
    name: "Latvia",
    flag: "https://flagcdn.com/lv.svg",
    code: "LV",
    areaCode: "371",
  },
  {
    name: "Lebanon",
    flag: "https://flagcdn.com/lb.svg",
    code: "LB",
    areaCode: "961",
  },
  {
    name: "Lesotho",
    flag: "https://flagcdn.com/ls.svg",
    code: "LS",
    areaCode: "266",
  },
  {
    name: "Liberia",
    flag: "https://flagcdn.com/lr.svg",
    code: "LR",
    areaCode: "231",
  },
  {
    name: "Libya",
    flag: "https://flagcdn.com/ly.svg",
    code: "LY",
    areaCode: "218",
  },
  {
    name: "Liechtenstein",
    flag: "https://flagcdn.com/li.svg",
    code: "LI",
    areaCode: "423",
  },
  {
    name: "Lithuania",
    flag: "https://flagcdn.com/lt.svg",
    code: "LT",
    areaCode: "370",
  },
  {
    name: "Luxembourg",
    flag: "https://flagcdn.com/lu.svg",
    code: "LU",
    areaCode: "352",
  },
  {
    name: "Macao",
    flag: "https://flagcdn.com/mo.svg",
    code: "MO",
    areaCode: "853",
  },
  {
    name: "North Macedonia",
    flag: "https://flagcdn.com/mk.svg",
    code: "MK",
    areaCode: "389",
  },
  {
    name: "Madagascar",
    flag: "https://flagcdn.com/mg.svg",
    code: "MG",
    areaCode: "261",
  },
  {
    name: "Malawi",
    flag: "https://flagcdn.com/mw.svg",
    code: "MW",
    areaCode: "265",
  },
  {
    name: "Malaysia",
    flag: "https://flagcdn.com/my.svg",
    code: "MY",
    areaCode: "60",
  },
  {
    name: "Maldives",
    flag: "https://flagcdn.com/mv.svg",
    code: "MV",
    areaCode: "960",
  },
  {
    name: "Mali",
    flag: "https://flagcdn.com/ml.svg",
    code: "ML",
    areaCode: "223",
  },
  {
    name: "Malta",
    flag: "https://flagcdn.com/mt.svg",
    code: "MT",
    areaCode: "356",
  },
  {
    name: "Marshall Islands",
    flag: "https://flagcdn.com/mh.svg",
    code: "MH",
    areaCode: "692",
  },
  {
    name: "Martinique",
    flag: "https://flagcdn.com/mq.svg",
    code: "MQ",
    areaCode: "596",
  },
  {
    name: "Mauritania",
    flag: "https://flagcdn.com/mr.svg",
    code: "MR",
    areaCode: "222",
  },
  {
    name: "Mauritius",
    flag: "https://flagcdn.com/mu.svg",
    code: "MU",
    areaCode: "230",
  },
  {
    name: "Mayotte",
    flag: "https://flagcdn.com/yt.svg",
    code: "YT",
    areaCode: "262",
  },
  {
    name: "Mexico",
    flag: "https://flagcdn.com/mx.svg",
    code: "MX",
    areaCode: "52",
  },
  {
    name: "Micronesia (Federated States of)",
    flag: "https://flagcdn.com/fm.svg",
    code: "FM",
    areaCode: "691",
  },
  {
    name: "Moldova (Republic of)",
    flag: "https://flagcdn.com/md.svg",
    code: "MD",
    areaCode: "373",
  },
  {
    name: "Monaco",
    flag: "https://flagcdn.com/mc.svg",
    code: "MC",
    areaCode: "377",
  },
  {
    name: "Mongolia",
    flag: "https://flagcdn.com/mn.svg",
    code: "MN",
    areaCode: "976",
  },
  {
    name: "Montenegro",
    flag: "https://flagcdn.com/me.svg",
    code: "ME",
    areaCode: "382",
  },
  {
    name: "Montserrat",
    flag: "https://flagcdn.com/ms.svg",
    code: "MS",
    areaCode: "1",
  },
  {
    name: "Morocco",
    flag: "https://flagcdn.com/ma.svg",
    code: "MA",
    areaCode: "212",
  },
  {
    name: "Mozambique",
    flag: "https://flagcdn.com/mz.svg",
    code: "MZ",
    areaCode: "258",
  },
  {
    name: "Myanmar",
    flag: "https://flagcdn.com/mm.svg",
    code: "MM",
    areaCode: "95",
  },
  {
    name: "Namibia",
    flag: "https://flagcdn.com/na.svg",
    code: "NA",
    areaCode: "264",
  },
  {
    name: "Nauru",
    flag: "https://flagcdn.com/nr.svg",
    code: "NR",
    areaCode: "674",
  },
  {
    name: "Nepal",
    flag: "https://flagcdn.com/np.svg",
    code: "NP",
    areaCode: "977",
  },
  {
    name: "Netherlands",
    flag: "https://flagcdn.com/nl.svg",
    code: "NL",
    areaCode: "31",
  },
  {
    name: "New Caledonia",
    flag: "https://flagcdn.com/nc.svg",
    code: "NC",
    areaCode: "687",
  },
  {
    name: "New Zealand",
    flag: "https://flagcdn.com/nz.svg",
    code: "NZ",
    areaCode: "64",
  },
  {
    name: "Nicaragua",
    flag: "https://flagcdn.com/ni.svg",
    code: "NI",
    areaCode: "505",
  },
  {
    name: "Niger",
    flag: "https://flagcdn.com/ne.svg",
    code: "NE",
    areaCode: "227",
  },
  {
    name: "Nigeria",
    flag: "https://flagcdn.com/ng.svg",
    code: "NG",
    areaCode: "234",
  },
  {
    name: "Niue",
    flag: "https://flagcdn.com/nu.svg",
    code: "NU",
    areaCode: "683",
  },
  {
    name: "Norfolk Island",
    flag: "https://flagcdn.com/nf.svg",
    code: "NF",
    areaCode: "672",
  },
  {
    name: "Korea (Democratic People's Republic of)",
    flag: "https://flagcdn.com/kp.svg",
    code: "KP",
    areaCode: "850",
  },
  {
    name: "Northern Mariana Islands",
    flag: "https://flagcdn.com/mp.svg",
    code: "MP",
    areaCode: "1",
  },
  {
    name: "Norway",
    flag: "https://flagcdn.com/no.svg",
    code: "NO",
    areaCode: "47",
  },
  {
    name: "Oman",
    flag: "https://flagcdn.com/om.svg",
    code: "OM",
    areaCode: "968",
  },
  {
    name: "Pakistan",
    flag: "https://flagcdn.com/pk.svg",
    code: "PK",
    areaCode: "92",
  },
  {
    name: "Palau",
    flag: "https://flagcdn.com/pw.svg",
    code: "PW",
    areaCode: "680",
  },
  {
    name: "Palestine, State of",
    flag: "https://flagcdn.com/ps.svg",
    code: "PS",
    areaCode: "970",
  },
  {
    name: "Panama",
    flag: "https://flagcdn.com/pa.svg",
    code: "PA",
    areaCode: "507",
  },
  {
    name: "Papua New Guinea",
    flag: "https://flagcdn.com/pg.svg",
    code: "PG",
    areaCode: "675",
  },
  {
    name: "Paraguay",
    flag: "https://flagcdn.com/py.svg",
    code: "PY",
    areaCode: "595",
  },
  {
    name: "Peru",
    flag: "https://flagcdn.com/pe.svg",
    code: "PE",
    areaCode: "51",
  },
  {
    name: "Philippines",
    flag: "https://flagcdn.com/ph.svg",
    code: "PH",
    areaCode: "63",
  },
  {
    name: "Pitcairn",
    flag: "https://flagcdn.com/pn.svg",
    code: "PN",
    areaCode: "64",
  },
  {
    name: "Poland",
    flag: "https://flagcdn.com/pl.svg",
    code: "PL",
    areaCode: "48",
  },
  {
    name: "Portugal",
    flag: "https://flagcdn.com/pt.svg",
    code: "PT",
    areaCode: "351",
  },
  {
    name: "Puerto Rico",
    flag: "https://flagcdn.com/pr.svg",
    code: "PR",
    areaCode: "1",
  },
  {
    name: "Qatar",
    flag: "https://flagcdn.com/qa.svg",
    code: "QA",
    areaCode: "974",
  },
  {
    name: "Republic of Kosovo",
    flag: "https://flagcdn.com/xk.svg",
    code: "XK",
    areaCode: "383",
  },
  {
    name: "Réunion",
    flag: "https://flagcdn.com/re.svg",
    code: "RE",
    areaCode: "262",
  },
  {
    name: "Romania",
    flag: "https://flagcdn.com/ro.svg",
    code: "RO",
    areaCode: "40",
  },
  {
    name: "Russian Federation",
    flag: "https://flagcdn.com/ru.svg",
    code: "RU",
    areaCode: "7",
  },
  {
    name: "Rwanda",
    flag: "https://flagcdn.com/rw.svg",
    code: "RW",
    areaCode: "250",
  },
  {
    name: "Saint Barthélemy",
    flag: "https://flagcdn.com/bl.svg",
    code: "BL",
    areaCode: "590",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "https://flagcdn.com/sh.svg",
    code: "SH",
    areaCode: "290",
  },
  {
    name: "Saint Kitts and Nevis",
    flag: "https://flagcdn.com/kn.svg",
    code: "KN",
    areaCode: "1",
  },
  {
    name: "Saint Lucia",
    flag: "https://flagcdn.com/lc.svg",
    code: "LC",
    areaCode: "1",
  },
  {
    name: "Saint Martin (French part)",
    flag: "https://flagcdn.com/mf.svg",
    code: "MF",
    areaCode: "590",
  },
  {
    name: "Saint Pierre and Miquelon",
    flag: "https://flagcdn.com/pm.svg",
    code: "PM",
    areaCode: "508",
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "https://flagcdn.com/vc.svg",
    code: "VC",
    areaCode: "1",
  },
  {
    name: "Samoa",
    flag: "https://flagcdn.com/ws.svg",
    code: "WS",
    areaCode: "685",
  },
  {
    name: "San Marino",
    flag: "https://flagcdn.com/sm.svg",
    code: "SM",
    areaCode: "378",
  },
  {
    name: "Sao Tome and Principe",
    flag: "https://flagcdn.com/st.svg",
    code: "ST",
    areaCode: "239",
  },
  {
    name: "Saudi Arabia",
    flag: "https://flagcdn.com/sa.svg",
    code: "SA",
    areaCode: "966",
  },
  {
    name: "Senegal",
    flag: "https://flagcdn.com/sn.svg",
    code: "SN",
    areaCode: "221",
  },
  {
    name: "Serbia",
    flag: "https://flagcdn.com/rs.svg",
    code: "RS",
    areaCode: "381",
  },
  {
    name: "Seychelles",
    flag: "https://flagcdn.com/sc.svg",
    code: "SC",
    areaCode: "248",
  },
  {
    name: "Sierra Leone",
    flag: "https://flagcdn.com/sl.svg",
    code: "SL",
    areaCode: "232",
  },
  {
    name: "Singapore",
    flag: "https://flagcdn.com/sg.svg",
    code: "SG",
    areaCode: "65",
  },
  {
    name: "Sint Maarten (Dutch part)",
    flag: "https://flagcdn.com/sx.svg",
    code: "SX",
    areaCode: "1",
  },
  {
    name: "Slovakia",
    flag: "https://flagcdn.com/sk.svg",
    code: "SK",
    areaCode: "421",
  },
  {
    name: "Slovenia",
    flag: "https://flagcdn.com/si.svg",
    code: "SI",
    areaCode: "386",
  },
  {
    name: "Solomon Islands",
    flag: "https://flagcdn.com/sb.svg",
    code: "SB",
    areaCode: "677",
  },
  {
    name: "Somalia",
    flag: "https://flagcdn.com/so.svg",
    code: "SO",
    areaCode: "252",
  },
  {
    name: "South Africa",
    flag: "https://flagcdn.com/za.svg",
    code: "ZA",
    areaCode: "27",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    flag: "https://flagcdn.com/gs.svg",
    code: "GS",
    areaCode: "500",
  },
  {
    name: "Korea (Republic of)",
    flag: "https://flagcdn.com/kr.svg",
    code: "KR",
    areaCode: "82",
  },
  {
    name: "Spain",
    flag: "https://flagcdn.com/es.svg",
    code: "ES",
    areaCode: "34",
  },
  {
    name: "Sri Lanka",
    flag: "https://flagcdn.com/lk.svg",
    code: "LK",
    areaCode: "94",
  },
  {
    name: "Sudan",
    flag: "https://flagcdn.com/sd.svg",
    code: "SD",
    areaCode: "249",
  },
  {
    name: "South Sudan",
    flag: "https://flagcdn.com/ss.svg",
    code: "SS",
    areaCode: "211",
  },
  {
    name: "Suriname",
    flag: "https://flagcdn.com/sr.svg",
    code: "SR",
    areaCode: "597",
  },
  {
    name: "Svalbard and Jan Mayen",
    flag: "https://flagcdn.com/sj.svg",
    code: "SJ",
    areaCode: "47",
  },
  {
    name: "Swaziland",
    flag: "https://flagcdn.com/sz.svg",
    code: "SZ",
    areaCode: "268",
  },
  {
    name: "Sweden",
    flag: "https://flagcdn.com/se.svg",
    code: "SE",
    areaCode: "46",
  },
  {
    name: "Switzerland",
    flag: "https://flagcdn.com/ch.svg",
    code: "CH",
    areaCode: "41",
  },
  {
    name: "Syrian Arab Republic",
    flag: "https://flagcdn.com/sy.svg",
    code: "SY",
    areaCode: "963",
  },
  {
    name: "Taiwan",
    flag: "https://flagcdn.com/tw.svg",
    code: "TW",
    areaCode: "886",
  },
  {
    name: "Tajikistan",
    flag: "https://flagcdn.com/tj.svg",
    code: "TJ",
    areaCode: "992",
  },
  {
    name: "Tanzania, United Republic of",
    flag: "https://flagcdn.com/tz.svg",
    code: "TZ",
    areaCode: "255",
  },
  {
    name: "Thailand",
    flag: "https://flagcdn.com/th.svg",
    code: "TH",
    areaCode: "66",
  },
  {
    name: "Timor-Leste",
    flag: "https://flagcdn.com/tl.svg",
    code: "TL",
    areaCode: "670",
  },
  {
    name: "Togo",
    flag: "https://flagcdn.com/tg.svg",
    code: "TG",
    areaCode: "228",
  },
  {
    name: "Tokelau",
    flag: "https://flagcdn.com/tk.svg",
    code: "TK",
    areaCode: "690",
  },
  {
    name: "Tonga",
    flag: "https://flagcdn.com/to.svg",
    code: "TO",
    areaCode: "676",
  },
  {
    name: "Trinidad and Tobago",
    flag: "https://flagcdn.com/tt.svg",
    code: "TT",
    areaCode: "1",
  },
  {
    name: "Tunisia",
    flag: "https://flagcdn.com/tn.svg",
    code: "TN",
    areaCode: "216",
  },
  {
    name: "Turkey",
    flag: "https://flagcdn.com/tr.svg",
    code: "TR",
    areaCode: "90",
  },
  {
    name: "Turkmenistan",
    flag: "https://flagcdn.com/tm.svg",
    code: "TM",
    areaCode: "993",
  },
  {
    name: "Turks and Caicos Islands",
    flag: "https://flagcdn.com/tc.svg",
    code: "TC",
    areaCode: "1",
  },
  {
    name: "Tuvalu",
    flag: "https://flagcdn.com/tv.svg",
    code: "TV",
    areaCode: "688",
  },
  {
    name: "Uganda",
    flag: "https://flagcdn.com/ug.svg",
    code: "UG",
    areaCode: "256",
  },
  {
    name: "Ukraine",
    flag: "https://flagcdn.com/ua.svg",
    code: "UA",
    areaCode: "380",
  },
  {
    name: "United Arab Emirates",
    flag: "https://flagcdn.com/ae.svg",
    code: "AE",
    areaCode: "971",
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    flag: "https://flagcdn.com/gb.svg",
    code: "GB",
    areaCode: "44",
  },
  {
    name: "United States of America",
    flag: "https://flagcdn.com/us.svg",
    code: "US",
    areaCode: "1",
  },
  {
    name: "Uruguay",
    flag: "https://flagcdn.com/uy.svg",
    code: "UY",
    areaCode: "598",
  },
  {
    name: "Uzbekistan",
    flag: "https://flagcdn.com/uz.svg",
    code: "UZ",
    areaCode: "998",
  },
  {
    name: "Vanuatu",
    flag: "https://flagcdn.com/vu.svg",
    code: "VU",
    areaCode: "678",
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    flag: "https://flagcdn.com/ve.svg",
    code: "VE",
    areaCode: "58",
  },
  {
    name: "Vietnam",
    flag: "https://flagcdn.com/vn.svg",
    code: "VN",
    areaCode: "84",
  },
  {
    name: "Wallis and Futuna",
    flag: "https://flagcdn.com/wf.svg",
    code: "WF",
    areaCode: "681",
  },
  {
    name: "Western Sahara",
    flag: "https://flagcdn.com/eh.svg",
    code: "EH",
    areaCode: "212",
  },
  {
    name: "Yemen",
    flag: "https://flagcdn.com/ye.svg",
    code: "YE",
    areaCode: "967",
  },
  {
    name: "Zambia",
    flag: "https://flagcdn.com/zm.svg",
    code: "ZM",
    areaCode: "260",
  },
  {
    name: "Zimbabwe",
    flag: "https://flagcdn.com/zw.svg",
    code: "ZW",
    areaCode: "263",
  },
];
